version: '2'

services:
  envoy:
    image: envoyproxy/envoy-alpine:latest
    ports:
    - 80:8000
    - 9000:9000
    volumes:
    - ./envoy.yaml:/etc/envoy.yaml
    command: envoy -c /etc/envoy.yaml
